server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth_route
              uri: lb:https://auth-service
              predicates:
                - Path=/api/auth/**

eureka:
  client:
    service-url:
      default-zone: http://${EUREKA_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
